AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function for logging S3 uploads

Parameters:
  LambdaRoleArn:
    Type: String
    Default: arn:aws:iam::724772072226:role/lambda-s3-logger-role

Resources:

  S3LoggerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: S3Logger
      Runtime: python3.9
      Role: !Ref LambdaRoleArn
      Handler: s3_logger.lambda_handler
      Code:
        S3Bucket: myprojects3bucket698
        S3Key: s3_logger.zip
      Timeout: 10
